config/routes.rb
Rails.application.routes.draw do
  resources :life_events
  resources :schools
  resources :people
  root 'home#index'

end

app/models/life_event.rb
class LifeEvent < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  #has_many :items
  has_many :schools
  has_many :life_events
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/life_events_controller.rb
class LifeEventsController < ApplicationController
  before_action :set_life_event, only: [:show, :edit, :update, :destroy]

  # GET /life_events
  def index
    @life_events = LifeEvent.all
  end

  # GET /life_events/1
  def show
  end

  # GET /life_events/new
  def new
    @life_event = LifeEvent.new
  end

  # GET /life_events/1/edit
  def edit
  end

  # POST /life_events
  def create
    @life_event = LifeEvent.new(life_event_params)

    respond_to do |format|
      if @life_event.save
        format.html { redirect_to @life_event, notice: 'Life event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /life_events/1
  def update
    respond_to do |format|
      if @life_event.update(life_event_params)
        format.html { redirect_to @life_event, notice: 'Life event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /life_events/1
  def destroy
    @life_event.destroy
    respond_to do |format|
      format.html { redirect_to life_events_url, notice: 'Life event was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life_event
      @life_event = LifeEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def life_event_params
      params.require(:life_event).permit(:name, :date, :description)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    respond_to do |format|
      format.html { redirect_to person_url, notice: 'Person was successfully deleted.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birthdate, :hometown)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  def index
    @schools = School.all
  end

  # GET /schools/1
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /schools/1
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /schools/1
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :startyear, :endyear)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/life_events_helper.rb
module LifeEventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/index.html.slim
h1 Shepard and Friends
h2 A Blog on Kicking Reaper Butt

h3= link_to "People", people_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Russo+One|Play' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/life_events/_form.html.slim
= form_for @life_event do |f|
  - if @life_event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@life_event.errors.count, "error")} prohibited this life event from being saved:"
      ul
        - @life_event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/life_events/edit.html.slim
h1 Edit Life Event

== render 'form'

= link_to 'Show', @life_event
'|
= link_to 'Back', life_events_path

app/views/life_events/index.html.slim
h1 Life Events

table
  thead
    tr
      th Event
      th Year
      th Description
      th
      th
      th

  tbody
    - @life_events.each do |life_event|
      tr
        td = life_event.name
        td = life_event.date
        td = life_event.description
        td = link_to 'Show', life_event
        td = link_to 'Edit', edit_life_event_path(life_event)
        td = link_to 'Remove', life_event, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Life Event', new_life_event_path
= link_to 'Home', root_path

app/views/life_events/new.html.slim
h1 Add New Life Event

== render 'form'

= link_to 'Back', life_events_path
= link_to 'Home', home_path

app/views/life_events/show.html.slim
p#notice = notice

p
  strong Name:
  = @life_event.name
p
  strong Date:
  = @life_event.date
p
  strong Description:
  = @life_event.description

= link_to 'Edit', edit_life_event_path(@life_event)
'|
= link_to 'Back', life_events_path

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :birthdate
    = f.text_field :birthdate
  .field
    = f.label :hometown
    = f.text_field :hometown
  .actions = f.submit

app/views/people/edit.html.slim
h1 Editing Person

== render 'form'

= link_to 'Show', @person
'|
= link_to 'Back', people_path

app/views/people/index.html.slim
h1 People


= link_to 'New Person', new_person_path
= link_to 'Home', root_path

app/views/people/new.html.slim
h1 Add New Person

== render 'form'

= link_to 'Back', people_path
= link_to 'Home', root_path

app/views/people/show.html.slim
p#notice = notice

p
  strong Name:
  = @person.name
p
  strong Birth Date:
  = @person.birthdate
p
  strong Home Town:
  = @person.hometown

= link_to 'Edit', edit_person_path(@person)
'|
= link_to 'Back', people_path

app/views/schools/_form.html.slim
= form_for @school do |f|
  - if @school.errors.any?
    #error_explanation
      h2 = "#{pluralize(@school.errors.count, "error")} prohibited this school from being saved:"
      ul
        - @school.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :startyear
    = f.text_field :startyear
  .field
    = f.label :endyear
    = f.text_field :endyear
  .actions = f.submit

app/views/schools/edit.html.slim
h1 Editing School

== render 'form'

= link_to 'Show', @school
'|
= link_to 'Back', schools_path

app/views/schools/index.html.slim
h1 Education

table
  thead
    tr
      th School
      th Start Year
      th End Year
      th
      th
      th

  tbody
    - @schools.each do |school|
      tr
        td = school.name
        td = school.startyear
        td = school.endyear
        td = link_to 'Show', school
        td = link_to 'Edit', edit_school_path(school)
        td = link_to 'Remove', school, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New School', new_school_path
= link_to 'Home', root_path

app/views/schools/new.html.slim
h1 Add New School

== render 'form'

= link_to 'Back', schools_path
= link_to 'Home', home_path

app/views/schools/show.html.slim
p#notice = notice

p
  strong Name:
  = @school.name
p
  strong Startyear:
  = @school.startyear
p
  strong Endyear:
  = @school.endyear

= link_to 'Edit', edit_school_path(@school)
'|
= link_to 'Back', schools_path